In [1]:
import numpy as np

In [3]:
arr = [[1,2],  [3,4]]
arr

[[1, 2], [3, 4]]

In [5]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [6]:
import torch

In [7]:
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
torch.ones(2,2)


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [11]:
np.random.rand(2,2)

array([[0.48739231, 0.85142569],
       [0.26877861, 0.54945769]])

In [12]:
torch.rand(2,2)


 0.3627  0.3743
 0.6926  0.9701
[torch.FloatTensor of size 2x2]